### PR TITLE
Polymer 3 prep

### PR DESCRIPTION
**Pull request by awikkerink**
* Update circleci publish creds to use context
* Rename .eslintrc to .eslintrc.json
* Add strip-whitespace
* Standardize lint scripts

### CODE REVIEW

**Comment by awikkerink** [comment]
ping @MichaelKovalchuk

**Comment by MichaelKovalchuk** [comment]
we may need to bump the lib version in package.json

**Comment by MichaelKovalchuk** [comment]
is it ready for merge?

**Comment by awikkerink** [comment]
Yup. Go for it

**Pull request merged**
